version: '3.8'
services:
  vite-app:
    build: . # find the Dockerfile in the current directory
    ports:
      - '5173:5173' # map port 5173 (Vite) in the container to the host machine's port 5173
    volumes:
      - .:/app # keeps the working directory in sync with actual project directory
      - /app/node_modules # ensures the container has its own node_modules directory to avoid conflicts
    command: npm run dev
