version: '3.8'
services:
  app:
    build:
      context: . # project root
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173" # map the frontend port
      - "3000:3000" # map the backend port
    volumes:
      - .:/app:cached # mounts project files for live changes without needing to rebuild container. cache to improve performance
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/palette-db
    command: sh -c "npm run migrate && npm run dev"
    platform: linux/arm64/v8

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: palette-db
    volumes:
      - pgdata:/var/lib/postgresql/data  # persists data within the container

volumes:
  pgdata: