name: ESLint and Prettier Checks

# trigger on PRs into main or dev and pushes to main or dev
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # setup node environment
      - name: Node setup
        uses: actions/setup-node@v3
        with:
            node-version: '22'

      # install dependencies
      - name: Install dependencies
        run: npm ci

      # generate Prisma client
      - name: Generate prisma client
        run: npm run generate

      # run ESLint
      - name: Run ESLint
        run: npm run lint

      # run Prettier
      - name: Run Prettier
        run: npm run prettier

      # build project
      - name: Build source code
        run: npm run build




